theme: jekyll-theme-cayman
docs:
  - title: Introduction
    url: index.md

  - title: Data Cleaning
    url: data_cleaning.html

  - title: Descriptive Analytics
    url: descriptive_analytics.html

  - title: Untitled
    url: Untitled.md

  - title: Descriptive Analytics
    url: descriptive_analytics_(US).md
